name: Publish Release

on:
  push:
    branches:
      - main

jobs:
  publish_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check commit message for keyword 'release'
      run: |
        echo "Checking commit message for keyword 'release'..."
        if ! grep -i "release" <<< "$(git log --pretty=format:"%s" -1)"; then
          echo "Commit does not contain keyword 'release'. Exiting."
          exit 78
        fi
    
    - name: Publish release
      run: echo "Publishing release"
