name: Release

on:
  push:
    branches:
      - main

jobs:
  publish_release_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checking commit message for keyword 'release'...
      run: |
        if ! git log -1 --pretty=%B | grep -q "release"; then
          echo "Commit does not contain keyword 'release'. Exiting."
          exit 78
        fi
