name: Release on Commit

on:
  push:
    branches:
      - main

jobs:
  release_job:
    runs-on: ubuntu-latest

    steps:
    - name: Check commit message
      run: |
        echo "Checking commit message for keyword 'release'..."
        if ! grep -i "release" <<< "$GITHUB_SHA"; then
          echo "Commit does not contain keyword 'release'. Exiting."
          exit 78
        fi
    - name: Publish Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v$(date +'%Y%m%d%H%M%S')"
        release_name: "Automatic Release $(date +'%Y-%m-%d %H:%M:%S')"
        draft: false
        prerelease: false
