name: Assign Reviewer

on:
  pull_request:
    branches: [main]

jobs:
  assign_reviewer_job:
    runs-on: ubuntu-latest

    steps:
    - name: Add Pull Request Reviewer
      uses: AveryCameronUofR/add-reviewer-gh-action@1.0.4
      with: 
        reviewers: "No3Mc"
        token: ${{ secrets.GITHUB_TOKEN }}
